### ISSUE TITLE
Is this actually still broken?

### ISSUE THREAD

**Issue by rsparkyc** [Clamb94/SimconnectAirportDataTest#1]
I just tried running this program but it seemed to work just fine, is it actually still broken for you?

**Comment by rsparkyc** [comment]
FWIW, I tried this by connecting to MSFS 2020, I only just assumed that's what you were using.

**Comment by Clamb94** [comment]
I've actually not tried it again since uploading it. Will give a try again next week and report back. Thanks for the info!

**Comment by rsparkyc** [comment]
Cool, when running it, I see this:
![image](https://github.com/Clamb94/SimconnectAirportDataTest/assets/2042290/0c24240a-cc9e-4d60-bdbe-f6656348d2cc)

**Comment by Clamb94** [comment]
It's now working for me as well. Thanks again for the heads up!
I've updated the code to also include an example how to get runway data, just as a reference in case anyone needs that.
